services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: app
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL","pg_isready -U app -d app"]
      interval: 5s
      timeout: 3s
      retries: 10

  api:
    build: ./api
    env_file: [.env]
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./api:/app
    command: >
      uvicorn app.main:app
      --host 0.0.0.0 --port 8000
      --reload
    expose:
      - "8000"

  web:
    build: ./web
    env_file: [.env]
    depends_on:
      - api
    volumes:
      - ./web:/usr/src/app
    command: ["npm","run","dev","--","--host"]
    expose:
      - "5173"

  nginx:
    build: ./nginx
    depends_on:
      - api
      - web
    ports:
      - "80:80"

volumes:
  pgdata:
