"""fix user.id to UUID

Revision ID: a58300d40bad
Revises: be1d7d5318f9
Create Date: 2025-08-19 14:05:26.248625

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op  # type: ignore

# revision identifiers, used by Alembic.
revision: str = "a58300d40bad"
down_revision: str | Sequence[str] | None = "be1d7d5318f9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("uq_conversations_pair"), table_name="conversations")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("uq_conversations_pair"),
        "conversations",
        [
            sa.literal_column("LEAST(user_a_id, user_b_id)"),
            sa.literal_column("GREATEST(user_a_id, user_b_id)"),
        ],
        unique=True,
    )
    # ### end Alembic commands ###
